# Generated by Django 5.1.2 on 2024-11-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_clientuser_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='engagement_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
